name: Test Bun and Installs Dependencies

on: [push, pull_request]


jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun Runtime
      uses: antongolub/action-setup-bun@v1
      with:
        bun-version: 0.1.0

    - name: Install Dependencies
      run: |
        bun install

    - name: Echo
      run: |
        echo "Dependencies installed"


